name: Build Krait Signal Handler

agent:
  type: Unity::VM::osx
  image: build-system/unity-extra-macos-10.13-katana:v0.3.6-621005
  flavor: b1.xlarge

commands:
  - perl build.pl

artifacts:
  artifacts:
    paths:
      - builds.zip
